# Properties App
server.port=8084

# MQTT Brokerdata
hivemq.uri=tcp://192.168.0.146:1883
hivemq.topic = ESP8266Client-Device/data
hivemq.clientid=ws-mqtt-savedata-dev
hivemq.username=ws-savedata
hivemq.password=123456

# MongoDB data
spring.data.mongodb.uri=mongodb://localhost/
spring.data.mongodb.port=27017
spring.data.mongodb.database= mqttdata

wsmqttsavedata.property=ws-mqtt-savedata-dev
